### ISSUE TITLE
AT-4.2: Access Candidate Info 

### ISSUE THREAD

**Issue by KhalilGarali** [vibqetowi/placeholder-soen341project2023#28]
# Issue Tracking

This acceptance test is for #13.

# User Acceptance Flow
- [x] The user logs in
- [x] The user can access /applicants route
- [x] The user clicks on the candidate that he wants to invite/accept/reject to the job

**Comment by walidoow** [comment]
https://user-images.githubusercontent.com/31325808/232184122-06ec90ad-a8e4-48eb-9019-ede38d912b60.mp4
